variable "name"                                 {}
variable "resource_group_name"                  {}
variable "location"                             {}
variable "sg_rule_name"                         {}
variable "sg_rule_description"                  {}
variable "sg_rule_priority"                     {}
variable "sg_rule_direction"                    {}
variable "sg_rule_access"                       {}
variable "sg_rule_protocol"                     {}
variable "sg_rule_source_port_range"            {}
variable "sg_rule_destination_port_range"       {}
variable "sg_rule_source_address_prefix"        {}
variable "sg_rule_destination_address_prefix"   {}